import { createElement } from '@lwc/engine-dom';
import FlowVariable_intoLWCDemo from 'c/flowVariable_intoLWCDemo';

describe('c-flow-variable-into-lwc-demo', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-flow-variable-into-lwc-demo', {
            is: FlowVariable_intoLWCDemo
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});